### ISSUE TITLE
Can not delete projects resources

### ISSUE THREAD

**Issue by displague** [crossplane-contrib/provider-tf-equinix-metal#7]
### What happened?
Can not delete projects resources:

```
  Warning  CannotObserveExternalResource  82s (x463 over 26m)  managed/project.equinixmetal.jet.crossplane.io/v1alpha1, kind=project  cannot run refresh: refresh failed: invalid value for payment_method_id (must be a valid UUID): : File name: main.tf.json
```

### How can we reproduce it?

Create the resources from examples/ and then try to delete it. Describe the resource.

### What environment did it happen in?
Crossplane version: 
provider-tf-equinix-metal 0.2.2

**Comment by displague** [comment]
Created a related issue on the Terraform project: https://github.com/equinix/terraform-provider-metal/issues/201

**Comment by muvaf** [comment]
Thanks for reporting @displague ! Does it work when you do provide a `payment_method_id`?

**Comment by muvaf** [comment]
FWIW, you can do schema manipulations specific to resources. For example, if you think that this field should be mandatory (at least till the fix in TF provider is in), you can make it so like here how we add a `region` field to all AWS resources except IAM: https://github.com/crossplane-contrib/provider-jet-aws/blob/main/config/overrides.go#L73

**Comment by displague** [comment]
Closing as won't fix, but this should be resolved in the replacement project.
See #11
